helpdesk_member_mailbox_collection:
    path:     /settings/mailbox
    controller: Webkul\UVDesk\MailboxBundle\Controller\MailboxChannel::listMailbox
    defaults: { panelId: 'settings' }

helpdesk_member_mailbox_collection_xhr:
    path:     /settings/mailbox/xhr
    controller: Webkul\UVDesk\MailboxBundle\Controller\MailboxChannelXHR::listMailboxXHR