helpdesk_member_mailbox_settings:
    path:     /settings/mailbox
    controller: Webkul\UVDesk\MailboxBundle\Controller\MailboxChannel::loadSettings
    defaults: { panelId: 'settings' }

helpdesk_member_mailbox_settings_create_mailbox_xhr:
    path:     /settings/mailbox/xhr/create
    controller: Webkul\UVDesk\MailboxBundle\Controller\MailboxChannelXHR::createMailbox

helpdesk_member_mailbox_settings_update_mailbox_xhr:
    path:     /settings/mailbox/xhr/update
    controller: Webkul\UVDesk\MailboxBundle\Controller\MailboxChannelXHR::updateMailbox

helpdesk_member_mailbox_settings_remove_mailbox_xhr:
    path:     /settings/mailbox/xhr/remove
    controller: Webkul\UVDesk\MailboxBundle\Controller\MailboxChannelXHR::removeMailbox
